apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l3awbma3h-go 
  janus-idp.io/tekton: l3awbma3h-go
  backstage.io/kubernetes-id: l3awbma3h-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l3awbma3h-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml